### Запрос на получение токена
POST http://localhost:5063/auth/login
Content-Type: application/json

{
  "username": "your-username",
  "password": "your-password"
}

### Запрос на доступ к защищенному эндпоинту с использованием сохраненного токена
GET http://localhost:5063/api/TEst/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ5b3VyLXVzZXJuYW1lIiwianRpIjoiYWFhMWMyOWItYTU0MS00NGNjLTkzNjYtZTMzMTA0MTYwYjA5IiwiZXhwIjoxNzMxMTY0NjE4LCJpc3MiOiJMaWJyYXJ5QXBpSXNzdWVyIiwiYXVkIjoiTGlicmFyeSJ9.crNnHP3qAUUWUwADrRwsfRnhzl7olE8WIG00_14_2wI